using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using TMPro;

public class GameController : MonoBehaviour
{
    public static GameController Instance { get; private set; }
    private string sceneToLoad; // Bi·∫øn l∆∞u t√™n scene c·∫ßn load
    private int currentLevelIndex = 0;
    
    void Awake()
    {
        
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;
        DontDestroyOnLoad(gameObject);
    }
    void OnEnable()
    {
        SceneSignal.OnLoadScene += LoadScene;
    }

    void OnDisable()
    {
        SceneSignal.OnLoadScene -= LoadScene;
    }

    void Start() 
    {
    }


    public void LoadScene(string sceneName)
    {
        if (sceneName == "BattleScene")
        {
            sceneToLoad = sceneName; // L∆∞u scene c·∫ßn load
            SceneManager.LoadScene("LoadingScene");
        }
        else
        {
            SceneManager.LoadScene(sceneName);
        }
    }

    public IEnumerator LoadTargetScene()
    {
        yield return new WaitForSeconds(0.5f); // Gi·∫£ l·∫≠p th·ªùi gian load UI

        AsyncOperation operation = SceneManager.LoadSceneAsync(sceneToLoad);
        operation.allowSceneActivation = false; // NgƒÉn scene m·ªõi t·ª± ƒë·ªông k√≠ch ho·∫°t

        while (!operation.isDone)
        {
            float progress = Mathf.Clamp01(operation.progress / 0.9f);
            LoadingController.Instance.UpdateProgress(progress); // üî• C·∫≠p nh·∫≠t progress bar

            if (operation.progress >= 0.9f)
            {
                yield return new WaitForSeconds(1f); // Gi·∫£ l·∫≠p th·ªùi gian ch·ªù
                operation.allowSceneActivation = true; // üî• K√≠ch ho·∫°t scene m·ªõi
            }

            yield return null;
        }
    }
    public void SetLevel(int level)
    {
        currentLevelIndex = level;
    }
    public int GetLevel()
    {
        return  currentLevelIndex;
    }
    
}
